apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-replica
  namespace: ${NAMESPACE}
spec:
  serviceName: "redis-cluster-service"
  replicas: 2
  selector:
    matchLabels:
      app: redis-replica
  template:
    metadata:
      labels:
        app: redis-replica
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          args:
            - redis-server
            - /config/redis.conf
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: redis-replica-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-replica-config
  namespace: ${NAMESPACE}
data:
  redis.conf: |
    # Redis Replica Configuration
    port 6379
    bind 0.0.0.0
    
    # Master settings - will be set dynamically via Sentinel
    # replicaof <masterip> <masterport>
    # masterauth ${REDIS_MASTER_PASSWORD}
    
    # Authentication
    requirepass ${REDIS_MASTER_PASSWORD}
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Memory management
    maxmemory-policy allkeys-lru
    
    # Networking
    tcp-keepalive 300
    
    # Logging
    loglevel notice
