apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
  namespace: ${NAMESPACE}
spec:
  clusterIP: None
  selector:
    app: redis-master
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-service
  namespace: ${NAMESPACE}
spec:
  clusterIP: None
  selector:
    app: redis-sentinel
  ports:
    - port: 26379
      targetPort: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: redis-sentinel
  ports:
    - port: 26379
      targetPort: 26379
      name: sentinel
---

apiVersion: v1
kind: Service
metadata:
  name: redis-master-clusterip
  namespace: ${NAMESPACE}
spec:
  selector:
    app: redis-master
  ports:
    - port: 6379
      targetPort: 6379
