apiVersion: v1
kind: PersistentVolume
metadata:
  name: browseterm-redis-pv
  namespace: ${NAMESPACE}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${REDIS_DATA_DIR}/browseterm-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: browseterm-redis-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: browseterm-redis
  namespace: ${NAMESPACE}
  labels:
    app: browseterm-redis
spec:
  containers:
  - name: redis
    image: redis:7-alpine
    ports:
    - containerPort: 6379
    args:
    - redis-server
    - --appendonly
    - "yes"
    - --save
    - "900 1"
    - --save
    - "300 10"
    - --save
    - "60 10000"
    volumeMounts:
    - name: redis-data
      mountPath: /data
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: browseterm-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: browseterm-redis-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: browseterm-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
